# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: gha runner development build

# description:
#
# Performs the development CI lifecycle steps for building pre-configured GitHub Action runners.
#
# Uses:
#   hadolint/hadolint-action
#   twplatformlabs/gha-tools-actions/buildx (using bake file for build configuration)
#   twplatformlabs/gha-tools-actions/scout-scan (Docker Scout cve scan)
#   (Optional) twplatformlabs/gha-tools-actions/bats (Runtime configuration testing option)
#   ossf/scorecard-action
#
#
# Use after-checkout local Action to setup ENV values as needed.
# Many steps provide additional configuration parameters. See inputs below
# for usage details and default settings. Additional step details are available
# in the associated twplatformlabs/gha-tools-actions repository.
# Includes Action hooks at:
# - after-checkout
# - before-build
# - after-build

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

    inputs:

      registry:
        description: OCI compatible registry. Default is docker.io.
        required: false
        type: string
        default: docker.io

      bake-file:
        description: Name of docker bake json file. Default is docker-bake.json.
        required: false
        type: string
        default: "docker-bake.json"
      tag:
        description: Value for development build tag. Default is dev.${GITHUB_SHA:0:7}.
        required: false
        type: string
        default: ""
      target:
        description: Bake file target to build. Default is runner.
        required: false
        type: string
        default: "runners"
      extra-build-args:
        description: Extra flags to pass to docker build
        required: false
        type: string
        default: ""

      skip-hadolint:
        description: Skip hadolint scan. Default is false.
        required: false
        type: string
        default: "false"
      hadolint-failure-threshold:
        description: Reporting error level. Default is info (error, warning, style, ignore)
        required: false
        type: string
        default: "info"
      hadolint-format:
        description: Hadolint output format. Default is tty.
        required: false
        type: string
        default: "tty"

      bats-test:
        description: Run bats test against container. Default is false.
        required: false
        type: string
        default: false
      bats-version:
        description: Install bats version. Default is skip.
        required: false
        type: string
        default: ""
      bats-run-container-name:
        description: Name for running container. Default is container-test.
        required: false
        type: string
        default: container-test
      bats-entry-point:
        description: Name of shell ( bash | ash | etc ). Default is /bin/bash.
        required: false
        type: string
        default: /bin/bash
      bats-test-path:
        description: Name of folder with bats tests. Default is test.
        required: false
        type: string
        default: test

      skip-cve-scan:
        description: Skip Docker Scout cve scan. Default is false.
        required: false
        type: string
        default: false

      op-version:
        description: Install 1password-cli version. Default is skip.
        required: false
        type: string
        default: ""
      teller-version:
        description: Install teller version. Default is skip.
        required: false
        type: string
        default: ""
      vault-version:
        description: Install vault version. Default is skip.
        required: false
        type: string
        default: ""
      scout-version:
        description: Install docker scout version. Default is skip.
        required: false
        type: string
        default: ""

      after-checkout:
        description: Optionally call ./.github/actions/after-checkout after code checkout. Default is skip.
        required: false
        type: string
        default: "false"
      before-build:
        description: Optionally call ./.github/actions/before-build before docker build. Default is skip.
        required: false
        type: string
        default: "false"
      after-build:
        description: Optionally call ./.github/actions/after-build after docker build. Default is skip.
        required: false
        type: string
        default: "false"

      builder-image-version:
        description: Define custom workflow runner image. Default is ghcr.io/twplatformlabs/gha-tools-runner:latest.
        type: string
        required: false
        default: "ghcr.io/twplatformlabs/gha-tools-runner:latest"

permissions:
  contents: write
  actions: read
  security-events: write

jobs:

  runner-dev-build:
    name: runner development build workflow
    runs-on: ubuntu-latest
    container: ${{ inputs.builder-image-version }}

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: run custom after-checkout action
        if: ${{ inputs.after-checkout != 'false' }}
        uses: ./.github/actions/after-checkout
        with:
          flag: ${{ inputs.after-checkout }}

      - name: install dev-release dependencies
        uses: twplatformlabs/gha-tools-actions/install@main
        with:
          op-version: ${{ inputs.op-version }}
          teller-version: ${{ inputs.teller-version }}
          vault-version: ${{ inputs.vault-version }}
          scout-version: ${{ inputs.scout-version }}
          snyk-version: ${{ inputs.snyk-version }}
          bats-version: ${{ inputs.bats-version }}

      - name: run custom before-build action
        if: ${{ inputs.before-build != 'false' }}
        uses: ./.github/actions/before-build
        with:
          flag: ${{ inputs.before-build }}

      - name: hadolint dockerfile
        if: ${{ inputs.skip-hadolint != 'true' }}
        uses: twplatformlabs/gha-tools-actions/hadolint@main
        with:
          bake-file: ${{ inputs.bake-file }}
          format: ${{ inputs.hadolint-format }}
          failure-threshold: ${{ inputs.hadolint-failure-threshold }}

      - name: confirm registry credentials and access
        uses: twplatformlabs/gha-tools-actions/confirm-registry@main
        with:
          registry: ${{ inputs.registry }}

      - name: build container images from docker bake file targets
        uses: twplatformlabs/gha-tools-actions/buildx@main
        with:
          bake-file: ${{ inputs.bake-file }}
          tag: ${{ inputs.tag}}
          target: ${{ inputs.target }}
          extra-build-args: ${{ inputs.extra-build-args }}

      - name: run bats test against running container, based on bake file targets
        if: ${{ inputs.bats-test == 'true' }}
        uses: twplatformlabs/gha-tools-actions/bats@main
        with:
          bake-file: ${{ inputs.bake-file }}
          tag: ${{ inputs.tag}}
          target: ${{ inputs.target }}
          bats-entry-point: ${{ inputs.bats-entry-point }}
          bats-test-path: ${{ inputs.bats-test-path }}

      - name: cve scan container images from docker bake file targets
        if: ${{ inputs.skip-cve-scan != 'true' }}
        uses: twplatformlabs/gha-tools-actions/scout-scan@main
        with:
          bake-file: ${{ inputs.bake-file }}
          tag: ${{ inputs.tag}}
          target: ${{ inputs.target }}

      - name: run custom after-build action
        if: ${{ inputs.after-build != 'false' }}
        uses: ./.github/actions/after-build
        with:
          flag: ${{ inputs.after-build }}
